### PR TITLE
utility to replace CWL expressions with either ExpressionTools or CommandLineTools

### PR DESCRIPTION
**Pull request by mr-c**
Goal: for those who want to add CWL execution support to existing or new workflow engines but don't want special handling of `ExpressionTools`, this utility can be run on user input (or adapted to be part of their codebase) to replace those `ExpressionTools` with `CommandLineTools` that have the same functionality.

CWL expressions/paramater references that are not possible to refactor (very rare): `inputs` or `outputs` with expressions in their `secondaryFiles` or `format` specification; having a dynamic input type signature seems like a bad idea and I will propose deprecating or removing it in CWL v2.0

Example input:
``` cwl
cwlVersion: v1.0
class: ExpressionTool
requirements:
  InlineJavascriptRequirement: {}
inputs:
  number: int
outputs:
  better_number: int
expression: >
  ${return {'better_number': inputs.number * 2};}
```
Becomes
``` cwl
#!/usr/bin/env cwl-runner
class: CommandLineTool
inputs:
- id: number
  type: int
outputs:
- id: bigger_number
  type: int
requirements:
- class: InitialWorkDirRequirement
  listing:
  - entryname: expression.js
    entry: |-
      "use strict";
      var inputs=$(inputs);
      var runtime=$(runtime);
      var ret = function(){return {'bigger_number': inputs.number * 2};}();
      process.stdout.write(JSON.stringify(ret));
hints:
- class: DockerRequirement
  dockerPull: node:slim
cwlVersion: v1.0
baseCommand:
- nodejs
- expression.js
stdout: cwl.output.json
```

NOTE: While support for `inputBinding.valueFrom` and `arguments[n].valueFrom` has been implemented, it has been turned off as this code can't currently deal with `File.path` references correctly. Galaxy-CWL doesn't need this, but if other users want this we can find a method to provide this as well.

- [ ] add tests
- [x] test a workflow that references an external `ExpressionTool`
- [ ] support saving new copies of external tools adjacent to the original one, or into a target directory
- [x] support `InlineJavascriptRequirement.expressionLib`
- [ ] Teach schema-salad's codegen tool to serialize in a better order (separate issue?)
- [x] Do the same for any `valueFrom` CWL Expression, creating new steps in the workflow
- [ ] run all CWL v1.0 conformance tests to check for corner cases
  - [ ] the above, but `cwltool --pack` first
- [x] add an option to only replace CWL expressions and leave ExpressionTools as is (requested by @jmchilton )
  - [ ] expose this option via a command line flag
- [ ] consolidate so there is only one `ExpressionTool`/`CommandLineTool` generated by this script per Workflow and per WorkflowStep. The later will combine any step level and Process level additions needed
- [ ] make a CWL v1.1 version of the script
- [x] add option to create sub-workflows, which would be less fragile for post-conversion editing
- [x] expose `Workflow.inputs` to the `ExpressionTool`/`CommandLineTool`s generated for `Workflow.requirements` CWL expressions.
- [x] detect CWL expressions that use the `$(`…`)` form in addition to the `${`…`}` form.
     (copy code from `cwltool` so we don't convert every single instance of `$(`…`)`, just the ones that need the expanded syntax

Places that can have CWL expressions:
(there is a table at the bottom of https://www.commonwl.org/user_guide/13-expressions/index.html)
- ~~Workflow.inputs[].format~~
- ~~Workflow.inputs[].secondaryFiles~~
- ~~Workflow.inputs[].secondaryFiles[]~~
- ~~Workflow.outputs[].format~~
- ~~Workflow.outputs[].secondaryFiles~~
- ~~Workflow.outputs[].secondaryFiles[]~~
- [x] CommandLineTool.arguments[]
- [x] CommandLineTool.arguments[].valueFrom
- [ ] CommandLineTool.stdin (v1.1 only)
- [x] CommandLineTool.stdout
- [x] CommandLineTool.stderr
- ~~CommandLineTool.inputs[].format~~
- ~~CommandLineTool.inputs[].secondaryFiles~~
- [x] CommandLineTool.inputs{].inputBinding.valueFrom
- [ ] CommandLineTool.outputs[].format
- ~~CommandLineTool.outputs[].secondaryFiles~~
- [x] CommandLineTool.outputs[].outputBinding.glob
- [x] CommandLineTool.outputs[].outputBinding.outputEval
- [x] ResourceRequirement.coresMin
- [x] ResourceRequirement.coresMax
- [x] ResourceRequirement.ramMin
- [x] ResourceRequirement.ramMax
- [x] ResourceRequirement.tmpdirMin
- [x] ResourceRequirement.tmpdirMax
- [x] ResourceRequirement.outdirMin
- [x] ResourceRequirement.outdirMax
- [x] InitialWorkDirRequirement.listing
- [x] InitialWorkDirRequirement.listing[]
- [x] InitialWorkDirRequirement.listing[] (when a Dirent).entry
- [x] InitialWorkDirRequirement.listing[] (when a Dirent).entryname
- [x] EnvVarRequirement.envDef[].envValue
- [x] Workflow.requirements.ResourceRequirement.coresMin
- [x] Workflow.requirements.ResourceRequirement.coresMax
- [x] Workflow.requirements.ResourceRequirement.ramMin
- [x] Workflow.requirements.ResourceRequirement.ramMax
- [x] Workflow.requirements.ResourceRequirement.tmpdirMin
- [x] Workflow.requirements.ResourceRequirement.tmpdirMax
- [x] Workflow.requirements.ResourceRequirement.outdirMin
- [x] Workflow.requirements.ResourceRequirement.outdirMax
- [x] Workflow.requirements.InitialWorkDirRequirement.listing
- [x] Workflow.requirements.InitialWorkDirRequirement.listing[]
- [x] Workflow.requirements.InitialWorkDirRequirement.listing[] (when a Dirent).entry
- [x] Workflow.requirements.InitialWorkDirRequirement.listing[] (when a Dirent).entryname
- [x] Workflow.requirements.EnvVarRequirement.envDef[].envValue
- [ ] Don't support any of the execution altering reqs under `hints` at any level, but do look for them and issue a loud warning

### CODE REVIEW

**Comment by kaushik-work** [comment]
Hi @mr-c could you please add some context to this (was it a response to an issue, a change to the spec, changes to the unit tests, etc.)

**Comment by mr-c** [comment]
@kaushik-work Done, thanks for asking!

**Comment by kaushik-work** [comment]
@mr-c very nice! Thanks!

**Comment by mr-c** [comment]
@susheel Here is the `InlineJavascriptRequirement` remover that I said that I'd write

**Comment by jmchilton** [comment]
Status:

- Spent a couple days getting cwl branch of Galaxy working with Python 3 and the latest cwltool and fixing regressions.
- Forked and added the ability to use more as a library https://github.com/jmchilton/cwl-utils/commit/5079edda07b54d1256f5bb97db6848062e7749bc (cherry-pick this?)
- Tried to just auto convert everything in Galaxy https://github.com/common-workflow-language/galaxy/commit/2213de83e5a62bcc0c2766de8df8c8557150ec26.
- Got it to the point where it didn't break existing passing tests:

```
./run_tests.sh -api lib/galaxy_test/api/test_cwl_conformance_green_v1_0.py::CwlConformanceTestCase::test_conformance_v1_0_step_input_default_value_nosource
```

But it does fail on the first random non-passing workflow test I found with errors seemingly in this code base:


```
./run_tests.sh -api lib/galaxy_test/api/test_cwl_conformance_v1_0.py::CwlConformanceTestCase::test_conformance_v1_0_wf_scatter_oneparam_valuefrom
```


```
[1m[31mERROR   [0m galaxy.web.framework.decorators:decorators.py:295 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/Users/john/workspace/galaxy/lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/Users/john/workspace/galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 381, in create
    return self.__api_import_new_workflow(trans, payload, **kwd)
  File "/Users/john/workspace/galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 638, in __api_import_new_workflow
    raw_workflow_description = self.__normalize_workflow(trans, data)
  File "/Users/john/workspace/galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 709, in __normalize_workflow
    return self.workflow_contents_manager.normalize_workflow_format(trans, as_dict)
  File "/Users/john/workspace/galaxy/lib/galaxy/managers/workflows.py", line 306, in normalize_workflow_format
    wf_proxy = workflow_proxy(workflow_path)
  File "/Users/john/workspace/galaxy/lib/galaxy/tool_util/cwl/parser.py", line 99, in workflow_proxy
    workflow = _to_cwl_workflow_object(workflow_path, strict_cwl_validation=strict_cwl_validation)
  File "/Users/john/workspace/galaxy/lib/galaxy/tool_util/cwl/parser.py", line 192, in _to_cwl_workflow_object
    cwl_workflow = _schema_loader(strict_cwl_validation).tool(path=workflow_path)
  File "/Users/john/workspace/galaxy/lib/galaxy/tool_util/cwl/schema.py", line 82, in tool
    raw_process_reference = self.raw_process_reference(kwds["path"])
  File "/Users/john/workspace/galaxy/lib/galaxy/tool_util/cwl/schema.py", line 47, in raw_process_reference
    etools_to_clt.main([path, galaxy_path])
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 28, in main
    result, modified = traverse(top, False)  # 2nd parameter: True to make CommandLineTools, False for ExpressionTools
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 107, in traverse
    return traverse_workflow(process, replace_etool)
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 961, in traverse_workflow
    step_modified = traverse_step(step, workflow)
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 913, in traverse_step
    self = example_input(type_for_source(parent, inp.source).type)
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 242, in type_for_source
    raise WorkflowException("param {} not found in {} or {}.".format(sourcename, cwl.save(process), cwl.save(parent)))
cwltool.errors.WorkflowException: param file:///Users/john/workspace/galaxy/test/functional/tools/cwl_tools/v1.0/scatter-valuefrom-wf1.cwl#inp not found in ordereddict([('class', 'Workflow'), ('id', 'file:///Users/john/workspace/galaxy/test/functional/tools/cwl_tools/v1.0/scatter-valuefrom-wf1.cwl'), ('inputs', [ordereddict([('id', 'inp'), ('type', ordereddict([('items', ordereddict([('name', 'instr'), ('fields', [ordereddict([('name', 'instr'), ('type', 'string')])]), ('type', 'record')])), ('type', 'array')]))])]), ('outputs', [ordereddict([('id', 'out'), ('outputSource', 'step1/echo_out'), ('type', ordereddict([('items', 'string'), ('type', 'array')]))])]), ('requirements', [ordereddict([('class', 'ScatterFeatureRequirement')]), ordereddict([('class', 'StepInputExpressionRequirement')])]), ('cwlVersion', 'v1.0'), ('steps', [ordereddict([('id', 'step1'), ('in', [ordereddict([('id', 'echo_in'), ('source', 'inp'), ('valueFrom', '$(self.instr)')]), ordereddict([('id', 'first'), ('source', 'inp'), ('valueFrom', '$(self[0].instr)')])]), ('out', ['echo_out']), ('run', ordereddict([('class', 'CommandLineTool'), ('id', '_:e5333cce-bd59-47ac-993b-71f033770499'), ('inputs', [ordereddict([('id', 'echo_in'), ('inputBinding', ordereddict([('position', 2)])), ('type', 'string')]), ordereddict([('id', 'first'), ('inputBinding', ordereddict([('position', 1)])), ('type', 'string')])]), ('outputs', [ordereddict([('id', 'echo_out'), ('outputBinding', ordereddict([('glob', 'step1_out'), ('loadContents', True), ('outputEval', '$(self[0].contents)')])), ('type', 'string')])]), ('hints', [{'ramMin': 8, 'class': 'ResourceRequirement'}]), ('baseCommand', 'echo'), ('arguments', ['-n', 'foo']), ('stdout', 'step1_out')])), ('scatter', 'echo_in')])])]) or None.
[1m[31mERROR   [0m galaxy.web.framework.decorators:decorators.py:295 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/Users/john/workspace/galaxy/lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/Users/john/workspace/galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 381, in create
    return self.__api_import_new_workflow(trans, payload, **kwd)
  File "/Users/john/workspace/galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 638, in __api_import_new_workflow
    raw_workflow_description = self.__normalize_workflow(trans, data)
  File "/Users/john/workspace/galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 709, in __normalize_workflow
    return self.workflow_contents_manager.normalize_workflow_format(trans, as_dict)
  File "/Users/john/workspace/galaxy/lib/galaxy/managers/workflows.py", line 306, in normalize_workflow_format
    wf_proxy = workflow_proxy(workflow_path)
  File "/Users/john/workspace/galaxy/lib/galaxy/tool_util/cwl/parser.py", line 99, in workflow_proxy
    workflow = _to_cwl_workflow_object(workflow_path, strict_cwl_validation=strict_cwl_validation)
  File "/Users/john/workspace/galaxy/lib/galaxy/tool_util/cwl/parser.py", line 192, in _to_cwl_workflow_object
    cwl_workflow = _schema_loader(strict_cwl_validation).tool(path=workflow_path)
  File "/Users/john/workspace/galaxy/lib/galaxy/tool_util/cwl/schema.py", line 82, in tool
    raw_process_reference = self.raw_process_reference(kwds["path"])
  File "/Users/john/workspace/galaxy/lib/galaxy/tool_util/cwl/schema.py", line 47, in raw_process_reference
    etools_to_clt.main([path, galaxy_path])
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 28, in main
    result, modified = traverse(top, False)  # 2nd parameter: True to make CommandLineTools, False for ExpressionTools
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 107, in traverse
    return traverse_workflow(process, replace_etool)
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 961, in traverse_workflow
    step_modified = traverse_step(step, workflow)
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 913, in traverse_step
    self = example_input(type_for_source(parent, inp.source).type)
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 242, in type_for_source
    raise WorkflowException("param {} not found in {} or {}.".format(sourcename, cwl.save(process), cwl.save(parent)))
cwltool.errors.WorkflowException: param file:///Users/john/workspace/galaxy/test/functional/tools/cwl_tools/v1.0/scatter-valuefrom-wf1.cwl#inp not found in ordereddict([('class', 'Workflow'), ('id', 'file:///Users/john/workspace/galaxy/test/functional/tools/cwl_tools/v1.0/scatter-valuefrom-wf1.cwl'), ('inputs', [ordereddict([('id', 'inp'), ('type', ordereddict([('items', ordereddict([('name', 'instr'), ('fields', [ordereddict([('name', 'instr'), ('type', 'string')])]), ('type', 'record')])), ('type', 'array')]))])]), ('outputs', [ordereddict([('id', 'out'), ('outputSource', 'step1/echo_out'), ('type', ordereddict([('items', 'string'), ('type', 'array')]))])]), ('requirements', [ordereddict([('class', 'ScatterFeatureRequirement')]), ordereddict([('class', 'StepInputExpressionRequirement')])]), ('cwlVersion', 'v1.0'), ('steps', [ordereddict([('id', 'step1'), ('in', [ordereddict([('id', 'echo_in'), ('source', 'inp'), ('valueFrom', '$(self.instr)')]), ordereddict([('id', 'first'), ('source', 'inp'), ('valueFrom', '$(self[0].instr)')])]), ('out', ['echo_out']), ('run', ordereddict([('class', 'CommandLineTool'), ('id', '_:e5333cce-bd59-47ac-993b-71f033770499'), ('inputs', [ordereddict([('id', 'echo_in'), ('inputBinding', ordereddict([('position', 2)])), ('type', 'string')]), ordereddict([('id', 'first'), ('inputBinding', ordereddict([('position', 1)])), ('type', 'string')])]), ('outputs', [ordereddict([('id', 'echo_out'), ('outputBinding', ordereddict([('glob', 'step1_out'), ('loadContents', True), ('outputEval', '$(self[0].contents)')])), ('type', 'string')])]), ('hints', [{'ramMin': 8, 'class': 'ResourceRequirement'}]), ('baseCommand', 'echo'), ('arguments', ['-n', 'foo']), ('stdout', 'step1_out')])), ('scatter', 'echo_in')])])]) or None.[1m[31mERROR   [0m galaxy.web.framework.decorators:decorators.py:295 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/Users/john/workspace/galaxy/lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/Users/john/workspace/galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 381, in create
    return self.__api_import_new_workflow(trans, payload, **kwd)
  File "/Users/john/workspace/galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 638, in __api_import_new_workflow
    raw_workflow_description = self.__normalize_workflow(trans, data)
  File "/Users/john/workspace/galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 709, in __normalize_workflow
    return self.workflow_contents_manager.normalize_workflow_format(trans, as_dict)
  File "/Users/john/workspace/galaxy/lib/galaxy/managers/workflows.py", line 306, in normalize_workflow_format
    wf_proxy = workflow_proxy(workflow_path)
  File "/Users/john/workspace/galaxy/lib/galaxy/tool_util/cwl/parser.py", line 99, in workflow_proxy
    workflow = _to_cwl_workflow_object(workflow_path, strict_cwl_validation=strict_cwl_validation)
  File "/Users/john/workspace/galaxy/lib/galaxy/tool_util/cwl/parser.py", line 192, in _to_cwl_workflow_object
    cwl_workflow = _schema_loader(strict_cwl_validation).tool(path=workflow_path)
  File "/Users/john/workspace/galaxy/lib/galaxy/tool_util/cwl/schema.py", line 82, in tool
    raw_process_reference = self.raw_process_reference(kwds["path"])
  File "/Users/john/workspace/galaxy/lib/galaxy/tool_util/cwl/schema.py", line 47, in raw_process_reference
    etools_to_clt.main([path, galaxy_path])
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 28, in main
    result, modified = traverse(top, False)  # 2nd parameter: True to make CommandLineTools, False for ExpressionTools
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 107, in traverse
    return traverse_workflow(process, replace_etool)
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 961, in traverse_workflow
    step_modified = traverse_step(step, workflow)
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 913, in traverse_step
    self = example_input(type_for_source(parent, inp.source).type)
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 242, in type_for_source
    raise WorkflowException("param {} not found in {} or {}.".format(sourcename, cwl.save(process), cwl.save(parent)))
cwltool.errors.WorkflowException: param file:///Users/john/workspace/galaxy/test/functional/tools/cwl_tools/v1.0/scatter-valuefrom-wf1.cwl#inp not found in ordereddict([('class', 'Workflow'), ('id', 'file:///Users/john/workspace/galaxy/test/functional/tools/cwl_tools/v1.0/scatter-valuefrom-wf1.cwl'), ('inputs', [ordereddict([('id', 'inp'), ('type', ordereddict([('items', ordereddict([('name', 'instr'), ('fields', [ordereddict([('name', 'instr'), ('type', 'string')])]), ('type', 'record')])), ('type', 'array')]))])]), ('outputs', [ordereddict([('id', 'out'), ('outputSource', 'step1/echo_out'), ('type', ordereddict([('items', 'string'), ('type', 'array')]))])]), ('requirements', [ordereddict([('class', 'ScatterFeatureRequirement')]), ordereddict([('class', 'StepInputExpressionRequirement')])]), ('cwlVersion', 'v1.0'), ('steps', [ordereddict([('id', 'step1'), ('in', [ordereddict([('id', 'echo_in'), ('source', 'inp'), ('valueFrom', '$(self.instr)')]), ordereddict([('id', 'first'), ('source', 'inp'), ('valueFrom', '$(self[0].instr)')])]), ('out', ['echo_out']), ('run', ordereddict([('class', 'CommandLineTool'), ('id', '_:e5333cce-bd59-47ac-993b-71f033770499'), ('inputs', [ordereddict([('id', 'echo_in'), ('inputBinding', ordereddict([('position', 2)])), ('type', 'string')]), ordereddict([('id', 'first'), ('inputBinding', ordereddict([('position', 1)])), ('type', 'string')])]), ('outputs', [ordereddict([('id', 'echo_out'), ('outputBinding', ordereddict([('glob', 'step1_out'), ('loadContents', True), ('outputEval', '$(self[0].contents)')])), ('type', 'string')])]), ('hints', [{'ramMin': 8, 'class': 'ResourceRequirement'}]), ('baseCommand', 'echo'), ('arguments', ['-n', 'foo']), ('stdout', 'step1_out')])), ('scatter', 'echo_in')])])]) or None.[1m[31mERROR   [0m galaxy.web.framework.decorators:decorators.py:295 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/Users/john/workspace/galaxy/lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/Users/john/workspace/galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 381, in create
    return self.__api_import_new_workflow(trans, payload, **kwd)
  File "/Users/john/workspace/galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 638, in __api_import_new_workflow
    raw_workflow_description = self.__normalize_workflow(trans, data)
  File "/Users/john/workspace/galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 709, in __normalize_workflow
    return self.workflow_contents_manager.normalize_workflow_format(trans, as_dict)
  File "/Users/john/workspace/galaxy/lib/galaxy/managers/workflows.py", line 306, in normalize_workflow_format
    wf_proxy = workflow_proxy(workflow_path)
  File "/Users/john/workspace/galaxy/lib/galaxy/tool_util/cwl/parser.py", line 99, in workflow_proxy
    workflow = _to_cwl_workflow_object(workflow_path, strict_cwl_validation=strict_cwl_validation)
  File "/Users/john/workspace/galaxy/lib/galaxy/tool_util/cwl/parser.py", line 192, in _to_cwl_workflow_object
    cwl_workflow = _schema_loader(strict_cwl_validation).tool(path=workflow_path)
  File "/Users/john/workspace/galaxy/lib/galaxy/tool_util/cwl/schema.py", line 82, in tool
    raw_process_reference = self.raw_process_reference(kwds["path"])
  File "/Users/john/workspace/galaxy/lib/galaxy/tool_util/cwl/schema.py", line 47, in raw_process_reference
    etools_to_clt.main([path, galaxy_path])
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 28, in main
    result, modified = traverse(top, False)  # 2nd parameter: True to make CommandLineTools, False for ExpressionTools
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 107, in traverse
    return traverse_workflow(process, replace_etool)
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 961, in traverse_workflow
    step_modified = traverse_step(step, workflow)
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 913, in traverse_step
    self = example_input(type_for_source(parent, inp.source).type)
  File "/Users/john/workspace/galaxy/.venv/src/cwl-utils/cwl_utils/etools_to_clt.py", line 242, in type_for_source
    raise WorkflowException("param {} not found in {} or {}.".format(sourcename, cwl.save(process), cwl.save(parent)))
cwltool.errors.WorkflowException: param file:///Users/john/workspace/galaxy/test/functional/tools/cwl_tools/v1.0/scatter-valuefrom-wf1.cwl#inp not found in ordereddict([('class', 'Workflow'), ('id', 'file:///Users/john/workspace/galaxy/test/functional/tools/cwl_tools/v1.0/scatter-valuefrom-wf1.cwl'), ('inputs', [ordereddict([('id', 'inp'), ('type', ordereddict([('items', ordereddict([('name', 'instr'), ('fields', [ordereddict([('name', 'instr'), ('type', 'string')])]), ('type', 'record')])), ('type', 'array')]))])]), ('outputs', [ordereddict([('id', 'out'), ('outputSource', 'step1/echo_out'), ('type', ordereddict([('items', 'string'), ('type', 'array')]))])]), ('requirements', [ordereddict([('class', 'ScatterFeatureRequirement')]), ordereddict([('class', 'StepInputExpressionRequirement')])]), ('cwlVersion', 'v1.0'), ('steps', [ordereddict([('id', 'step1'), ('in', [ordereddict([('id', 'echo_in'), ('source', 'inp'), ('valueFrom', '$(self.instr)')]), ordereddict([('id', 'first'), ('source', 'inp'), ('valueFrom', '$(self[0].instr)')])]), ('out', ['echo_out']), ('run', ordereddict([('class', 'CommandLineTool'), ('id', '_:e5333cce-bd59-47ac-993b-71f033770499'), ('inputs', [ordereddict([('id', 'echo_in'), ('inputBinding', ordereddict([('position', 2)])), ('type', 'string')]), ordereddict([('id', 'first'), ('inputBinding', ordereddict([('position', 1)])), ('type', 'string')])]), ('outputs', [ordereddict([('id', 'echo_out'), ('outputBinding', ordereddict([('glob', 'step1_out'), ('loadContents', True), ('outputEval', '$(self[0].contents)')])), ('type', 'string')])]), ('hints', [{'ramMin': 8, 'class': 'ResourceRequirement'}]), ('baseCommand', 'echo'), ('arguments', ['-n', 'foo']), ('stdout', 'step1_out')])), ('scatter', 'echo_in')])])]) or None.
```

**Pull request merged**
