### PR TITLE
docker_extract: support CWL v1.1 and v1.2 

### PR DESCRIPTION
**Pull request by manabuishii**
Current version using v1.0 so can not process v1.1 and v1.2.

Fixes: #219

### CODE REVIEW

**Review by mr-c — CHANGES_REQUESTED** [review]
Can we do the `cwlVersion` check and use the appropriate parser instead of hard coding it?

**Comment by manabuishii** [comment]
@mr-c Thanks comment.
I think [Using the CWL Parsers](../#using-the-cwl-parsers) help to do it.
I'll try to implement it.

**Comment by mr-c** [comment]
@manabuishii , @tom-tan 's #99 has been merged, which should help

**Comment by jfennick** [comment]
I've also just been affected by this issue, although I am able to restrict to v1.0 for now.

Here is a minimal reproducible example:

```
cwlVersion: v1.0
class: CommandLineTool
requirements:
  DockerRequirement:
    dockerPull: hello-world
inputs: {}
outputs:
  stdout:
    type: File
    outputBinding:
      glob: stdout
stdout: stdout
```
This works, but if you change to v1.1 or v1.2 you get:

```
$ cwl-docker-extract -s images/ hello-world.cwl
Traceback (most recent call last):
  File "/home/fennickjr/mambaforge-pypy3/envs/cwl-utils/bin/cwl-docker-extract", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/fennickjr/mambaforge-pypy3/envs/cwl-utils/lib/python3.11/site-packages/cwl_utils/docker_extract.py", line 114, in main
    sys.exit(run(parse_args(sys.argv[1:])))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fennickjr/mambaforge-pypy3/envs/cwl-utils/lib/python3.11/site-packages/cwl_utils/docker_extract.py", line 47, in run
    top = cwl.load_document(args.input)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fennickjr/mambaforge-pypy3/envs/cwl-utils/lib/python3.11/site-packages/cwl_utils/parser/cwl_v1_0.py", line 13599, in load_document
    result, metadata = _document_load(
                       ^^^^^^^^^^^^^^^
  File "/home/fennickjr/mambaforge-pypy3/envs/cwl-utils/lib/python3.11/site-packages/cwl_utils/parser/cwl_v1_0.py", line 679, in _document_load
    return _document_load_by_url(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fennickjr/mambaforge-pypy3/envs/cwl-utils/lib/python3.11/site-packages/cwl_utils/parser/cwl_v1_0.py", line 755, in _document_load_by_url
    _document_load(
  File "/home/fennickjr/mambaforge-pypy3/envs/cwl-utils/lib/python3.11/site-packages/cwl_utils/parser/cwl_v1_0.py", line 714, in _document_load
    loader.load(doc, baseuri, loadingOptions, docRoot=baseuri),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fennickjr/mambaforge-pypy3/envs/cwl-utils/lib/python3.11/site-packages/cwl_utils/parser/cwl_v1_0.py", line 532, in load
    raise ValidationException("", None, errors, "-")
schema_salad.exceptions.ValidationException: - tried CommandLineTool but
  Trying 'CommandLineTool'
    the `cwlVersion` field is not valid because:
      - tried <class 'NoneType'> but
        Expected a type but got str
      - tried CWLVersion but
        Expected one of ('draft-2', 'draft-3.dev1', 'draft-3.dev2', 'draft-3.dev3', 'draft-3.dev4', 'draft-3.dev5', 'draft-3', 'draft-4.dev1', 'draft-4.dev2', 'draft-4.dev3', 'v1.0.dev4', 'v1.0')
- tried ExpressionTool but
  Not a ExpressionTool
- tried Workflow but
  Not a Workflow
- tried array<CommandLineTool | ExpressionTool | Workflow> but
  Expected a list, was <class 'dict'>
```

**Review by mr-c — APPROVED** [review]

**Pull request merged**
